apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  namespace: development # _{_NAMESPACE_}_
  labels:
    app: solar-system
spec:
  replicas: 2 # _{_REPLICAS_}_
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: kescefko/solar-system:b3cd461fbb2aaf00eb59508ddd51095583fe8e9c # _{_IMAGE_}_
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 512Mi
        envFrom:
        - secretRef:
            name: mongo-db-creds
