apiVersion: v1
kind: Service
metadata:
  name: astro-bot-ui
  namespace: astro-bot
  labels:
    app: astro-bot-ui
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    app: astro-bot-ui

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: solar-system
#   name: solar-system
#   namespace: _{_NAMESPACE_}_
# spec:
#   ports:
#   - port: 3000
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     app: solar-system 
#   type: NodePort